---
-  name: Replace Cisco IOS-XE Router Configurations
   connection: local
   hosts: cisco-ios-xe-routers
   gather_facts: no
   vars:
     creds:
       hostname: "{{ ansible_host }}"
       username: "{{ username }}"
       password: "{{ password }}"
       dev_os: "{{ device_type }}"
   tags: ios-xe
   tasks:
      - napalm_install_config:
            provider: "{{ creds }}"
            config_file: "{{ lookup('pipe', 'ls -1 backup/{{ inventory_hostname }}_config.**') }}"
            commit_changes: True
            replace_config: True
